external_components:
  - source: component
    refresh: 0s

esphome:
  name: klima_wohnzimmer

esp8266:
  board: esp01_1m  
  
api:
ota:
web_server:
  port: 80
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


logger:
  baud_rate: 0 # disable serial logging if you're using the standard TX/RX pins for your serial peripheral
  level: DEBUG

uart:
   tx_pin: 1         # hardware dependant
   rx_pin: 3         # hardware dependant
   baud_rate: 9600
   parity: EVEN
  
button:
  - platform: restart
    name: "Living Room Restart"

climate:
  - platform: sharp_ac       # adjust to match your AC unit!
    name: "Living Room AC"

